### ISSUE TITLE
Personality of player

### ISSUE THREAD

**Issue by Basstrack** [xAranaktu/FC-24-CM-Cheat-Table#12]
So the personality it is just a question/issue or maybe a idea im not sure if i increase the personality of my player lets say  maverick to 100,000 why doesnt it say X% more  it will stay the same cant you add a feature that changes the percentage? say my percentage of maverick is  20% i want to increase why doesnt it change? say i changed to 100% then i should unlock all the playstyles of that personality??

**Comment by xAranaktu** [comment]
Set 100,000 for Maverick and change the rest to 0 and you will have 100% on Maverick. I don't get what's the problem.

**Comment by Basstrack** [comment]
Ohh! my bad, Idk how it works
