### ISSUE TITLE
Is there any way to customize players' transfer in career mode?

### ISSUE THREAD

**Issue by GotGimhong** [xAranaktu/FC-24-CM-Cheat-Table#18]
Hi bro, the feature of customizing players' transfer in fifa19 cheat table was fantastic, but I cannot find the same feature in fc24 cheat table (in fact, I cannot find the same feature in fifa23 cheat table too). Could you show me a way to customize players' transfer in career mode?

**Comment by xAranaktu** [comment]
Players can be transferred only with the help of live editor. [Here's how to do it](https://github.com/xAranaktu/FC-24-Live-Editor/wiki/Player-Transfers)
