### ISSUE TITLE
No more updates ?

### ISSUE THREAD

**Issue by AmrKhan25** [xAranaktu/FC-24-CM-Cheat-Table#19]
Just wondering
And quick question in Fifa19 CT the clone feature doesn't work is it because the website it tries to connect to is no longer working or is it another issue 🤔

**Comment by xAranaktu** [comment]
Ye, I don't plan any update for cheat table.
FIFA 19 CT is using official easports site to load fut data and this site was shutdown long time ago I think.

**Comment by AmrKhan25** [comment]
> FIFA 19 CT is using official easports site to load fut data and this site was shutdown long time ago I think.

Any chance you can provide a way to change the links even manually

**Comment by xAranaktu** [comment]
Replacing the link won't work. Like, which website you want to use instead? There is no other website with exact same endpoints. You will need to rewrite the whole functionality. CT is open source at the end of the day, so you can do it by yourself if you want.
The original url you can find in [fut_requests.lua](https://github.com/xAranaktu/FIFA-19---Career-Mode-Cheat-Table/blob/master/FIFA%2019%20-%20CM%20Cheat%20Table/lua/fut_requests.lua)
