### ISSUE TITLE
Attributes my player are reset in career mode

### ISSUE THREAD

**Issue by Cheshirskycat** [xAranaktu/FC-24-CM-Cheat-Table#21]
After applying the attributes no matter what I did: I saved the game immediately, applied right before the match, tried to change after the match and save. The result is always the same - the attributes are changed back.

**Comment by xAranaktu** [comment]
It's normal and nothing can be done with that.
Use [999 skill points script](https://github.com/xAranaktu/fc-24-CM-Cheat-Table/wiki/999-Skill-Points) or "freeze" the attributes with [live editor](https://github.com/xAranaktu/FC-24-Live-Editor/wiki/Editing-VPRO)

**Comment by Cheshirskycat** [comment]
but how freeze in live editor, i search on wiki, but I didn't find there information how exactly to freeze values there, or did it mean in the CE table itself ?
