### ISSUE TITLE
Player Career play as Player Sqad Role

### ISSUE THREAD

**Issue by AndaleObe** [xAranaktu/FC-24-CM-Cheat-Table#22]
hello pawel,

could you tell me in which file the sqad role for play as player is? so that you are always manually in the starting 11. I'm trying to edit it on the PS4 because the files are the same as on the PC. thank you very much

**Comment by xAranaktu** [comment]
I don't know in which file. Cheat Table and Live Editor changes what's stored in memory. This data later is saved in careerfile, but afaik. there is no that complex save editor for FIFA which will allow you to change that.

**Comment by AndaleObe** [comment]
> I don't know in which file. Cheat Table and Live Editor changes what's stored in memory. This data later is saved in careerfile, but afaik. there is no that complex save editor for FIFA which will allow you to change that.

OK, thank you very much anyway
