### ISSUE TITLE
Cheat Engine

### ISSUE THREAD

**Issue by AndaleObe** [xAranaktu/FC-24-CM-Cheat-Table#23]
hey pawel,

I found the point youthhacademyenabled via cheat engine. Can you please help me find the value from 1 to 0 or 0 to 1? I've been looking for this for so long. thank you very much

![Unbenannt](https://github.com/xAranaktu/FC-24-CM-Cheat-Table/assets/53269821/69bbeb9f-28ac-40d1-8e49-33219ab55a2d)

**Comment by xAranaktu** [comment]
You just found const string. This isn't enough to disable or enable youth academy.
