### ISSUE TITLE
Impossible to go beyond 2048

### ISSUE THREAD

**Issue by Bismoons** [xAranaktu/FC-24-CM-Cheat-Table#24]
Hello, First of all, I would like to point out that my English is bad and I apologize for that.

I use the cheat table very regularly to extend my career beyond the 15-year limit.

However, I have a problem since I arrived at the 2045 season. Indeed, when I renew the contracts of my players, instead of indicating their number of years remaining, it indicates "2043, 0 months" and at the end of the season, they are all free agents.
Since the "contractvaliduntil" value is coded on 11 bits, it is logical that the limit is 2047 at most.

I tried to change the number of bits to 12 to be able to go further than 2047 but the problem remains the same.

Could you tell me if it is possible to resolve this bug?

Thank you for taking the time to address my issue.

![Capture d'écran 2024-04-22 190937](https://github.com/xAranaktu/FC-24-CM-Cheat-Table/assets/167800573/2cf9169b-c44f-450c-a2ad-059d56a97a8b)

**Comment by xAranaktu** [comment]
I don't know any method which will allow you to go beyond limits defined in the game database, sorry.
