### ISSUE TITLE
GUI does not load

### ISSUE THREAD

**Issue by uijiamu** [xAranaktu/FC-24-CM-Cheat-Table#28]
I downloaded the latest version of FC24 from the Euro Cup and the cheat table stopped working. I thought it was because of the old version, but I downloaded the latest one and it stopped working anyway. I have installed it correctly and start it with the live editor and in offline mode. The GUI stays with the phrase "Attached to the game progress" and the "ready to use" message does not appear. I have tried everything but I can't find a solution to the problem, I tried previous versions but it doesn't work anymore either.

Attached image
![Captura de pantalla 2024-06-07 005551](https://github.com/xAranaktu/FC-24-CM-Cheat-Table/assets/172001938/770175f3-05fb-4d25-9b44-e13f92ef8771)

**Comment by HeilShukla** [comment]
I am facing the same issue

**Comment by uijiamu** [comment]
The problem occurs with the TU15, I just returned to the TU14 version and it works perfectly for me

**Comment by HeilShukla** [comment]
Guess we have to wait for a new version of the cheat table to play TU15?

**Comment by rydawg94** [comment]
Same issue for me

**Comment by xAranaktu** [comment]
Fixed in [FC 24 Cheat Table v24.1.1.2](https://www.patreon.com/posts/105754110)
