### ISSUE TITLE
Baseplayerid is nil when cloning a player in GUI

### ISSUE THREAD

**Issue by tranvan1202** [xAranaktu/FC-24-CM-Cheat-Table#30]
Hi xAranaktu team,
Thank you for your tool, but I'm facing an issue when Cloning a player from the GUI Screen, please have a look at the attached screenshot and help us fix it if you can.
![image](https://github.com/xAranaktu/FC-24-CM-Cheat-Table/assets/32728582/492371b4-97c2-4e0e-afab-ce31b0f483aa)
Thanks.

**Comment by xAranaktu** [comment]
The data is loaded from futbin.com. This website recently got updated and cheat table is no longer able to read the data properly from there. Nothing you can do with that I guess.

@Aranaktu
The data is loaded from futbin.com. This website recently got updated and cheat table is no longer able to read the data properly from there. Nothing you can do with that I guess.
