### ISSUE TITLE
need help with lua script

### ISSUE THREAD

**Issue by Jellyman1196** [xAranaktu/FC-24-CM-Cheat-Table#35]
i try to open it and it doesn't opne because it says " The lua sript in this trainer has some issuses and will therefor not load "
![Screenshot 2024-07-12 170757](https://github.com/user-attachments/assets/d9f980ab-4548-496b-b5ab-fcf7d0925a4c)

**Comment by Jellyman1196** [comment]
![Screenshot 2024-07-12 171623](https://github.com/user-attachments/assets/df938161-a9b8-46ab-9786-abff4eb52675)
and this

**Comment by joaozindelas** [comment]
im getting the same thing idk what to do

**Comment by xAranaktu** [comment]
Read [Troubleshooting](https://github.com/xAranaktu/FC-24-CM-Cheat-Table/wiki/Troubleshooting)
