### ISSUE TITLE
Cheat table unlimited replacements

### ISSUE THREAD

**Issue by lumpinee** [xAranaktu/FC-24-CM-Cheat-Table#37]
I noticed that from the cheat table it does not allow me to activate unlimited substitutions. I asked a friend and he also has this problem. I read the description that this problem has been solved. but unfortunately it still persists. How can I solve it?

**Comment by xAranaktu** [comment]
EA is switching between two versions of the code. It depends on game patch. If your game is up to date (TU18.2) then use CT v24.1.1.3
