### ISSUE TITLE
Club switching error

### ISSUE THREAD

**Issue by wben3305** [xAranaktu/FC-24-CM-Cheat-Table#39]
Cut to the chase, I've been having trouble with switch to a new club (using club ID in Job offers). The game let me take the job successfully, unfortunately, every time I go to **Squad hub** , it crashes immediately . (I've been using the latest LE and CT version.) 
If anyone who has found the solution, please give me an answer. Thanks for reading.
![Screenshot 2024-08-21 231623](https://github.com/user-attachments/assets/37a7ac91-e4d8-42fb-b24f-26f2cab97c68)

**Comment by xAranaktu** [comment]
This is not issue with the tool.
If it happens only in Ajax then you have corrupted player in your squad. I guess the only thing you can try is to release players from your team with live editor until your game stop crashing.
