### ISSUE TITLE
Manager carrer is slow

### ISSUE THREAD

**Issue by Moritz123455** [xAranaktu/FC-24-CM-Cheat-Table#4]
hi the live editor works perfect and the CT to but when you simulate to the next game calendar or normal its so slow i have to wait 1-2 minutes to come from 12 july to 1 august

**Comment by DeKuTx** [comment]
its not about the cheat table. its ea's fault, when you play without connecting to the ea servers (basically playing offline) for no reason the game becomes much slower. (sorry for late comment)

**Comment by iamfc24player** [comment]
> its not about the cheat table. its ea's fault, when you play without connecting to the ea servers (basically playing offline) for no reason the game becomes much slower. (sorry for late comment)

a tip to fix it is:
turn ea offline by going into the ea thing and 2 lines
click it and go offline
turn internet on
fixed and you can sim fast again
