### ISSUE TITLE
Live Editor: Crash caused by entering player editor after importing miniface

### ISSUE THREAD

**Issue by DinoHuT** [xAranaktu/FC-24-CM-Cheat-Table#5]
I imported a miniface via the live editor.
After i suceesfuly imported the miniface it crashed and gave me  a DirectX function ERROR
Everytime i try to access this specific player it crashes.
I can still edit him through Cheat Engine soo no rush.
Also i konvertet the image gimp dunno if that might be important

The direct error message is:

DirectX function "GetDeviceRemovedReason" failed with 
DXGI_ERROR_INVALID_CALL ("The application provided invalid
parameter data; this must be debugged and fixed before the 
application is released."). GPU: " NVIDIA GeForce RTX 2080",
Driver: 54601

Also sorry if that might be already a known issue couldn't find it
Best regards

**Comment by xAranaktu** [comment]
The miniface you have imported is invalid and causing the crash. Not a bug. 
Read https://github.com/xAranaktu/FC-24-Live-Editor/wiki/Importing-Miniface
