### ISSUE TITLE
Can't open the Cheat Table

### ISSUE THREAD

**Issue by adiagustin** [xAranaktu/FC-24-CM-Cheat-Table#8]
Hello, i have issues.

I can't open the cheat table, always show the notification "lua/GUI/forms/playerseditform/manager.lua:5492: attempt to index a nil value (field 'TraitsTab')".. Please help me
![Screenshot_2](https://github.com/xAranaktu/FC-24-CM-Cheat-Table/assets/33904477/58695b43-e3ce-4011-af72-df52a90e3bf0)

**Comment by BestGamer954** [comment]
Change the end of the file from cetrainer to ct, it worked for me

**Comment by adiagustin** [comment]
> Change the end of the file from cetrainer to ct, it worked for me

How to change it?

**Comment by adiagustin** [comment]
> Change the end of the file from cetrainer to ct, it worked for me

Nice.. i can open now. but i have a new problem when im excute a lua
![Screenshot_3](https://github.com/xAranaktu/FC-24-CM-Cheat-Table/assets/33904477/4bf5a577-e04b-41cc-8efc-4b8b55ef980d)
